name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        core-branch: [ main ]  # Adjust branches/tags as needed
        gradle-plugin-branch: [ main ]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: SetUp ois-core
        run: |
          git clone --branch ${{ matrix.core-branch }} https://github.com/attiasas/ois-core.git
          cd ois-core
          chmod +x gradlew
          ./gradlew publishToMavenLocal
          cd ..  # Return to the main project working directory
        shell: bash

      - name: SetUp ois-gradle-plugin
        run: |
          git clone --branch ${{ matrix.gradle-plugin-branch }} https://github.com/attiasas/ois-gradle-plugin.git
          cd ois-core
          chmod +x gradlew
          ./gradlew publishToMavenLocal
          cd ..  # Return to the main project working directory
        shell: bash

      # Extract version from the release tag
      - name: Extract Version
        id: extract_version
        run: |
          # Extract the version from the GitHub release tag (e.g., v1.2.3)
          VERSION=${{ github.event.release.tag_name }}
          # Remove leading "v" if present (e.g., "v1.2.3" -> "1.2.3")
          VERSION=${VERSION#v}
          
          # Update gradle.properties and action env with the new version
          sed -i "s/^version=.*/version=${VERSION}/" gradle.properties
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          # Verify the change
          echo "Updated version in gradle.properties:"
          grep '^version=' gradle.properties || echo "version property not found"

      # Build the project and create a ZIP
      - name: Build Project
        run: ./gradlew clean build

      # Upload the ZIP file generated by the build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/distributions/ois-idea-plugin-${{ env.VERSION }}.zip
          asset_name: ois-idea-plugin-${{ env.VERSION }}.zip
          asset_content_type: application/zip