name: "Compatibility verification"

on: [ push, pull_request ]

jobs:
  test:
    runs-on: macOS-latest
    name: Compatibility verification
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      # Run compatibility verification
      - name: Compatibility verification
        run: ./gradlew clean verifyPlugin runPluginVerifier