name: "Compatibility verification"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macOS-latest
    name: Compatibility verification
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Give permission to gradlew
        run: chmod +x gradlew
        if: runner.os != 'Windows'

      # Run compatibility verification
      - name: Compatibility verification
        run: ./gradlew clean verifyPlugin runPluginVerifier