name: "Compatibility verification"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        core-branch: [dev_mode]  # Adjust branches/tags as needed
        gradle-plugin-branch: [dev_mode]
    name: Compatibility verification
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: SetUp ois-core
        run: |
          git clone --branch ${{ matrix.core-branch }} https://github.com/attiasas/ois-core.git
          cd ois-core
          chmod +x gradlew
          ./gradlew publishToMavenLocal
          cd ..  # Return to the main project working directory
        shell: bash

      - name: SetUp ois-gradle-plugin
        run: |
          git clone --branch ${{ matrix.gradle-plugin-branch }} https://github.com/attiasas/ois-gradle-plugin.git
          cd ois-core
          chmod +x gradlew
          ./gradlew publishToMavenLocal
          cd ..  # Return to the main project working directory
        shell: bash

      # Run compatibility verification
      - name: Compatibility verification
        run: ./gradlew clean verifyPlugin runPluginVerifier